### ISSUE TITLE
推荐源

### ISSUE THREAD

**Issue by zhangzhuheng** [chinesehuazhou/python-weekly#1]
* [This Week in Python](https://bas.codes/)
* [Python⇒Speed](https://pythonspeed.com/)
* [捕蛇者说](https://pythonhunter.org/)
* [Python Weekly](https://www.pythonweekly.com/)
* [蠎周刊](https://weekly.pychina.org/issue/issue-578.html)

另外，请问本周刊有RSS订阅吗

**Comment by chinesehuazhou** [comment]
> * [This Week in Python](https://bas.codes/)
> * [Python⇒Speed](https://pythonspeed.com/)
> * [捕蛇者说](https://pythonhunter.org/)
> 
> 另外，请问本周刊有RSS订阅吗

感谢分享！第一个我没见过，很需要这类源，再次感谢！

有博客的RSS：https://pythoncat.top/rss.xml

**Comment by zhangzhuheng** [comment]
@chinesehuazhou 不客气，我又添加了一个。很高兴看到这个系列，会持续关注。希望有单独的订阅方式。如果你是固定通过MR或commit更新本仓库，我订阅Github MR或commit也可以。

**Comment by chinesehuazhou** [comment]
@zhangzhuheng 谢谢，新加的也是我未关注的。RSS没做分离。可以关注commit
