### ISSUE TITLE
【开源自荐】Pydumpling: Python Debug工具，与linux下面调试core dump文件一样，支持在异常发生时/程序任意位置保留当前调用栈帧，然后通过Pdb进行调试。

### ISSUE THREAD

**Issue by cocolato** [chinesehuazhou/python-weekly#14]
项目地址： https://github.com/cocolato/pydumpling
在线文档：https://pydumpling.readthedocs.io/en/latest/

Feature：
- 支持在任何地方保存Python调用栈帧，而不是只在异常发生的时候
- 支持多种pdb拓展工具(pdb++、ipdb)
- 支持开启全局hook，自动对程序运行过程中的异常栈进行转储，减少代码侵入
- 提供了一个方便用来调试的命令行工具
- 支持服务器远程调试(remote pdb)

pydumpling可以在代码的任何位置中，将当前Python程序的栈帧以backtrace的形式写到一个文件中，可以稍后在Python调试器(pdb)中加载它。目前pydump支持很多兼容PDB api的调试器（pdbpp, udb, ipdb)

**Comment by chinesehuazhou** [comment]
谢谢投稿，将收录在本周发布的第43期
