### ISSUE TITLE
【推荐文章】Python Monthly Topics （日语）

### ISSUE THREAD

**Issue by NoHeartPen** [chinesehuazhou/python-weekly#16]
文章地址： https://gihyo.jp/list/group/Python-Monthly-Topics
推荐理由：收录了日本开发者撰写的与 Python 有关热点话题组成的系列文章（目前有25篇，从2022年7月开始，大致按照每月一期的频率更新）。涵盖的话题比较广：从 Python 的新特性，到热门的第三方库的介绍（Python in Excel、PyScript、基于 Rust 的 Polars、uv），再到 Python 的应用场景（Sphinx 部署文档、Cloudflare Workers 部署无服务器的 Python 代码）。因为投稿会由日本出版公司「技术评论社」（类似人民邮电出版社）的编辑审核，每篇文章质量都很高，虽然暂时没有发现人工的中文翻译，但还是想推荐大家读读。

**Comment by chinesehuazhou** [comment]
@NoHeartPen 谢谢分享！才看到，今天周刊已发，下周收录哈～

**Comment by NoHeartPen** [comment]
好耶，我看之前都是猫哥你在收进周刊了后关的，我就不关啦。另，我之后尽量不在周六分享了，这样我们都有更多时间整理（笑

**Comment by chinesehuazhou** [comment]
@NoHeartPen 已分享在第64期
