### ISSUE TITLE
flasky-cli 一个Flask项目脚手架

### ISSUE THREAD

**Issue by un4gt** [chinesehuazhou/python-weekly#17]
一个用于快速初始化 flask项目的脚手架。
目前支持以下的项目模板：
- [Flask-API](https://github.com/un4gt/Flask-API)
- [cookiecutter-Flask-Foundation](https://github.com/JackStouffer/cookiecutter-Flask-Foundation)
- [cookiecutter-flask](https://github.com/cookiecutter-flask/cookiecutter-flask)
- [cookiecutter-flask-minimal](https://github.com/candidtim/cookiecutter-flask-minimal)
- [cookiecutter-flask-skeleton](https://github.com/testdrivenio/cookiecutter-flask-skeleton)

目前正计划添加更多有用的模板和其他的功能
项目地址：[un4gt/flasky-cli: CLI to start Flask projects](https://github.com/un4gt/flasky-cli)
PyPi 地址：[flasky-cli · PyPI](https://pypi.org/project/flasky-cli/)

**Comment by chinesehuazhou** [comment]
已分享在第67期
