### ISSUE TITLE
推荐文章：我买了本豆瓣 9.6 分的 Python 书，发现里面每 5 页一个错误？！

### ISSUE THREAD

**Issue by TheFry2** [chinesehuazhou/python-weekly#2]
文章地址：https://juejin.cn/post/7240248679515963451

推荐理由：分析一本出版物中的 30 项错误，教学相关 Python 知识。

**Comment by chinesehuazhou** [comment]
@TheFry2 非常好，感谢推荐！
里面有些话题我也写过，比如第一条中文变量名的（https://pythoncat.top/posts/2021-01-13-books）

另外，我也补充一些信息：
1. 我本人也觉得三引号注释法有点奇怪，不过这却是Guido曾推荐过的写法 https://pythoncat.top/posts/2020-07-19-comments

2. 说没有switch语句，这没错。一般的switch与match-case还是挺不同的吧，只是它没提后者，确实不该

。。。

**Comment by chinesehuazhou** [comment]
@TheFry2  下期收录。另外想问，这篇文章可以单独转载到公众号么，会注明来源出处

**Comment by TheFry2** [comment]
> @TheFry2 下期收录。另外想问，这篇文章可以单独转载到公众号么，会注明来源出处

可以的，谢谢。
