### ISSUE TITLE
推荐文章：Relieving your Python packaging pain

### ISSUE THREAD

**Issue by NoHeartPen** [chinesehuazhou/python-weekly#3]
文章地址：https://www.bitecode.dev/p/relieving-your-python-packaging-pain

推荐理由： 关于 Python 环境管理，作者提供了六点建议，并解释了为什么建议这么做。

我在看了周刊第一期的 [[吐槽] conda 真是太难用了！ 如何优雅地管理 Python 环境？](https://www.v2ex.com/t/938669#reply88)  后，开始关注这个问题，但一直没有找到比较系统的总结，看了这篇文章后终于有了大致的思路（这篇文章不仅写了「怎么做」，还写了「为什么」，让我改掉了不建虚拟环境的陋习和放弃折腾 conda）。

另外，CSDN 上有翻译版 [如何减轻 Python 打包之痛](https://blog.csdn.net/csdnnews/article/details/131546123) 。

**Comment by chinesehuazhou** [comment]
@NoHeartPen 谢谢投稿，下期收录～
