### ISSUE TITLE
你好,我是python3新手,已學過一些基礎內容,有幾個問題想請寧提供相關資訊:

### ISSUE THREAD

**Issue by Oscor** [chinesehuazhou/python-weekly#4]
你好,我是python3新手,已學過一些基礎內容,有幾個問題想請寧提供相關資訊:
1:想往python的核心繼續學習(如:解釋器的實現,或者是其核心代碼)
2:目前正在學習"機器學習的部分",請問,這部分有什麼可推薦的資料嗎?(請以從入門到專業順序推薦)

**Comment by chinesehuazhou** [comment]
@Oscor 
1、书籍推荐《Fluent Python》、《CPython Internals》
2、我不太了解机器学习领域，建议可从Github 上搜索相关资料，比如这个：https://github.com/ashishpatel26/500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code
