### ISSUE TITLE
在开源周刊里放收费教程是不是不太合适

### ISSUE THREAD

**Issue by Mekako** [chinesehuazhou/python-weekly#5]
Week6里的一篇文章，点进去只是大体介绍，具体源码还得付费获取，我理解知识付费，但还是建议这种收费教程在标题里就提前标记一下（收费）
![image](https://github.com/chinesehuazhou/python-weekly/assets/113497377/17d92bfd-69a4-4121-b973-f20f0750e41e)

**Comment by chinesehuazhou** [comment]
@Mekako 谢谢指出！这种不合适推荐，我会把它删掉
