### ISSUE TITLE
投稿： RSS-OPML-to-Markdown 加强版

### ISSUE THREAD

**Issue by AboutRSS** [chinesehuazhou/python-weekly#7]
Repo:
https://github.com/AboutRSS/RSS-OPML-to-Markdown

介绍请见：
https://t.me/s/aboutrss/1387

祝越办越好！

**Comment by chinesehuazhou** [comment]
@AboutRSS 已分享于第27期：https://github.com/chinesehuazhou/python-weekly/blob/main/docs/2023-11-18-weekly.md
